---
heat_template_version: 2017-09-01

description: Create a stack for Jenkins masters and slaves.

parameters:
  flavor_compute:
    type: string
    label: Instance Type
    default: VeryLarge_Linux
  flavor_controller:
    type: string
    label: Instance Type
    default: VeryLarge_Linux
  flavor_bastion:
    type: string
    label: Instance Type
    default: Small_Linux
  image:
    type: string
    label: Image ID
    description: Image to be used for compute instance.
    default: CentOS-7.4-N1
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance.
    default: mykey
    constraints:
      - custom_constraint: nova.keypair

  volume_size_docker:
    type: number
    description: Size of the attached volume.
    default: 50
  volume_size_ceph:
    type: number
    description: Size of the attached volume.
    default: 30

  compute_metadata:
    type: json
    label: Metadata
  controller_metadata:
    type: json
    label: Metadata
  bastion_metadata:
    type: json
    label: Metadata

  hypadmin_network_gateway:
    type: string
    default: 10.0.2.254
  hypadmin_network_name:
    type: string
    default: hypadmin_network
  hypadmin_network_cidr:
    type: string
    default: 10.0.2.0/24

  floating_network_name:
    type: string
    default: floating_network
  floating_network_cidr:
    type: string
    default: 10.0.6.0/24

  ceph_mgmt_network_name:
    type: string
    default: ceph_mgmt_network
  ceph_mgmt_network_cidr:
    type: string
    default: 10.0.3.0/24
  ceph_cluster_network_name:
    type: string
    default: ceph_cluster_network
  ceph_cluster_network_cidr:
    type: string
    default: 10.0.4.0/24

  internal_network_cidr:
    type: string
    default: 10.0.7.0/24
  internal_network_name:
    type: string
    default: internal_network

  public_network_gateway:
    type: string
    default: 10.0.5.254
  public_network_name:
    type: string
    default: public_network
  public_network_cidr:
    type: string
    default: 10.0.5.0/24

  internal_vip:
    type: string
    default: 10.0.7.1
  public_vip:
    type: string
    default: 10.0.5.1

  instance_security_name:
    type: string
    default: instance_security_openstack

  external:
    type: string
    description: Network externe for floating IP
    default: external

resources:
  hypadmin_network:
    type: OS::Openstack::Hypadmin
    properties:
      hypadmin_network_name: { get_param: hypadmin_network_name }
      hypadmin_network_cidr: { get_param: hypadmin_network_cidr }
      hypadmin_network_gateway: { get_param: hypadmin_network_gateway }

  public_network:
    type: OS::Openstack::Public
    properties:
      public_network_name: { get_param: public_network_name }
      public_network_cidr: { get_param: public_network_cidr }
      public_network_gateway: { get_param: public_network_gateway }

  floating_network:
    type: OS::Openstack::Floating
    properties:
      floating_network_name: { get_param: floating_network_name }
      floating_network_cidr: { get_param: floating_network_cidr }

  internal_network:
    type: OS::Openstack::Internal
    properties:
      internal_network_name: { get_param: internal_network_name }
      internal_network_cidr: { get_param: internal_network_cidr }

  ceph_cluster_network:
    type: OS::Openstack::CephCluster
    properties:
      ceph_cluster_network_name: { get_param: ceph_cluster_network_name }
      ceph_cluster_network_cidr: { get_param: ceph_cluster_network_cidr }

  ceph_mgmt_network:
    type: OS::Openstack::CephMgmt
    properties:
      ceph_mgmt_network_name: { get_param: ceph_mgmt_network_name }
      ceph_mgmt_network_cidr: { get_param: ceph_mgmt_network_cidr }

  instance_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: { get_param: instance_security_name }
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: 112
          remote_ip_prefix: 0.0.0.0/0

  controller_1:
    type:  OS::Openstack::Controllers
    depends_on: [ public_network, ceph_mgmt_network, ceph_cluster_network, internal_network, floating_network, hypadmin_network, instance_security_group ]
    properties:
      name: controller-1
      flavor: { get_param: flavor_controller }
      image: { get_param: image }
      key_name: { get_param: key_name }
      volume_size_docker: { get_param: volume_size_docker }
      server_data: { get_param: controller_metadata }
      hypadmin_network: { get_param: hypadmin_network_name }
      ceph_mgmt_network: { get_param: ceph_mgmt_network_name }
      ceph_cluster_network: { get_param: ceph_cluster_network_name }
      public_network: { get_param: public_network_name }
      floating_network: { get_param: floating_network_name }
      internal_network: { get_param: internal_network_name }
      instance_security_group: { get_param: instance_security_name }
      hypadmin_ip: 10.0.2.2
      ceph_mgmt_ip: 10.0.3.2
      ceph_cluster_ip: 10.0.4.2
      public_ip: 10.0.5.2
      floating_ip: 10.0.6.2
      internal_ip: 10.0.7.2
      public_vip: 10.0.5.1
      internal_vip: 10.0.7.1

  controller_2:
    type:  OS::Openstack::Controllers
    depends_on: [ public_network, ceph_mgmt_network, ceph_cluster_network, internal_network, floating_network, hypadmin_network, instance_security_group ]
    properties:
      name: controller-2
      flavor: { get_param: flavor_controller }
      image: { get_param: image }
      key_name: { get_param: key_name }
      volume_size_docker: { get_param: volume_size_docker }
      server_data: { get_param: controller_metadata }
      hypadmin_network: { get_param: hypadmin_network_name }
      ceph_mgmt_network: { get_param: ceph_mgmt_network_name }
      ceph_cluster_network: { get_param: ceph_cluster_network_name }
      public_network: { get_param: public_network_name }
      floating_network: { get_param: floating_network_name }
      internal_network: { get_param: internal_network_name }
      instance_security_group: { get_param: instance_security_name }
      hypadmin_ip: 10.0.2.3
      ceph_mgmt_ip: 10.0.3.3
      ceph_cluster_ip: 10.0.4.3
      public_ip: 10.0.5.3
      floating_ip: 10.0.6.3
      internal_ip: 10.0.7.3
      public_vip: 10.0.5.1
      internal_vip: 10.0.7.1

  controller_3:
    type:  OS::Openstack::Controllers
    depends_on: [ public_network, ceph_mgmt_network, ceph_cluster_network, internal_network, floating_network, hypadmin_network, instance_security_group ]
    properties:
      name: controller-3
      flavor: { get_param: flavor_controller }
      image: { get_param: image }
      key_name: { get_param: key_name }
      volume_size_docker: { get_param: volume_size_docker }
      server_data: { get_param: controller_metadata }
      hypadmin_network: { get_param: hypadmin_network_name }
      ceph_mgmt_network: { get_param: ceph_mgmt_network_name }
      ceph_cluster_network: { get_param: ceph_cluster_network_name }
      public_network: { get_param: public_network_name }
      floating_network: { get_param: floating_network_name }
      internal_network: { get_param: internal_network_name }
      instance_security_group: { get_param: instance_security_name }
      hypadmin_ip: 10.0.2.4
      ceph_mgmt_ip: 10.0.3.4
      ceph_cluster_ip: 10.0.4.4
      public_ip: 10.0.5.4
      floating_ip: 10.0.6.4
      internal_ip: 10.0.7.4
      public_vip: 10.0.5.1
      internal_vip: 10.0.7.1

  compute_1:
    type: OS::Openstack::Compute
    depends_on: [ ceph_mgmt_network, ceph_cluster_network, internal_network, hypadmin_network, instance_security_group ]
    properties:
      name: compute-1
      flavor: { get_param: flavor_compute }
      image: { get_param: image }
      key_name: { get_param: key_name }
      volume_size_docker: { get_param: volume_size_docker }
      volume_size_ceph: { get_param: volume_size_ceph }
      server_data: { get_param: controller_metadata }
      hypadmin_network: { get_param: hypadmin_network_name }
      ceph_mgmt_network: { get_param: ceph_mgmt_network_name }
      ceph_cluster_network: { get_param: ceph_cluster_network_name }
      internal_network: { get_param: internal_network_name }
      instance_security_group: { get_param: instance_security_name }
      hypadmin_ip: 10.0.2.12
      ceph_mgmt_ip: 10.0.3.12
      ceph_cluster_ip: 10.0.4.12
      internal_ip: 10.0.7.12

  compute_2:
    type: OS::Openstack::Compute
    depends_on: [ ceph_mgmt_network, ceph_cluster_network, internal_network, hypadmin_network, instance_security_group ]
    properties:
      name: compute-2
      flavor: { get_param: flavor_compute }
      image: { get_param: image }
      key_name: { get_param: key_name }
      volume_size_docker: { get_param: volume_size_docker }
      volume_size_ceph: { get_param: volume_size_ceph }
      server_data: { get_param: controller_metadata }
      hypadmin_network: { get_param: hypadmin_network_name }
      ceph_mgmt_network: { get_param: ceph_mgmt_network_name }
      ceph_cluster_network: { get_param: ceph_cluster_network_name }
      internal_network: { get_param: internal_network_name }
      instance_security_group: { get_param: instance_security_name }
      hypadmin_ip: 10.0.2.13
      ceph_mgmt_ip: 10.0.3.13
      ceph_cluster_ip: 10.0.4.13
      internal_ip: 10.0.7.13

  compute_3:
    type: OS::Openstack::Compute
    depends_on: [ ceph_mgmt_network, ceph_cluster_network, internal_network, hypadmin_network, instance_security_group ]
    properties:
      name: compute-3
      flavor: { get_param: flavor_compute }
      image: { get_param: image }
      key_name: { get_param: key_name }
      volume_size_docker: { get_param: volume_size_docker }
      volume_size_ceph: { get_param: volume_size_ceph }
      server_data: { get_param: controller_metadata }
      hypadmin_network: { get_param: hypadmin_network_name }
      ceph_mgmt_network: { get_param: ceph_mgmt_network_name }
      ceph_cluster_network: { get_param: ceph_cluster_network_name }
      internal_network: { get_param: internal_network_name }
      instance_security_group: { get_param: instance_security_name }
      hypadmin_ip: 10.0.2.14
      ceph_mgmt_ip: 10.0.3.14
      ceph_cluster_ip: 10.0.4.14
      internal_ip: 10.0.7.14

  bastion:
    type: OS::Openstack::Bastion
    depends_on: [ public_network, floating_network, hypadmin_network, instance_security_group ]
    properties:
      name: bastion
      flavor: { get_param: flavor_bastion }
      image: { get_param: image }
      key_name: { get_param: key_name }
      volume_size_docker: { get_param: volume_size_docker }
      server_data: { get_param: bastion_metadata }
      hypadmin_network: { get_param: hypadmin_network_name }
      public_network: { get_param: public_network_name }
      floating_network: { get_param: floating_network_name }
      instance_security_group: { get_param: instance_security_name }
      hypadmin_ip: 10.0.2.100
      public_ip: 10.0.5.100
      floating_ip: 10.0.6.100
